theme: jekyll-theme-minimal
[user]
email=llexbridge@gmail.com
name=liangyq4040
$ yum install curl-devel
$ # cd to wherever the source for git is
$ cd /usr/local/src/git-1.7.9
$ ./configure
$ make
$ make install
